project_id = "hyackhbgbiunkijipqhk"

[functions.send-application-notification]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = false

[functions.setup-2fa]
verify_jwt = false

[functions.check-2fa-required]
verify_jwt = false
